routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');

        Route::get('/', 'Admin\AdminRevenueController@main_dashboard')->name('dashboard');
        
        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/verify_badge', 'Admin\AdminUserController@users_verify_badge_status')->name('users.verify_badge');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/billing_accounts','Admin\AdminUserController@billing_accounts_index')->name('users.billing_accounts');


        Route::get('user_subscription_payments/index','Admin\AdminUserController@user_subscription_payments')->name('users_subscriptions.index');

        Route::get('user_subscriptions_payment/view','Admin\AdminUserController@user_subscriptions_payment_view')->name('user_subscriptions.view');

        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        Route::get('users/upgrade_account', 'Admin\AdminUserController@user_upgrade_account')->name('users.upgrade_account');

        //followers
         Route::get('followers' , 'Admin\AdminUserController@user_followers')->name('user_followers');

        Route::get('followings', 'Admin\AdminUserController@user_followings')->name('user_followings');

        //user products CRUD Operations

        Route::get('products', 'Admin\AdminProductController@user_products_index')->name('user_products.index');

        Route::get('products/create', 'Admin\AdminProductController@user_products_create')->name('user_products.create');

        Route::get('products/edit', 'Admin\AdminProductController@user_products_edit')->name('user_products.edit');

        Route::post('products/save', 'Admin\AdminProductController@user_products_save')->name('user_products.save');

        Route::get('products/view', 'Admin\AdminProductController@user_products_view')->name('user_products.view');

        Route::get('products/delete', 'Admin\AdminProductController@user_products_delete')->name('user_products.delete');

        Route::get('products/status', 'Admin\AdminProductController@user_products_status')->name('user_products.status');

        Route::get('products/dashboard', 'Admin\AdminProductController@user_products_dashboard')->name('user_products.dashboard');

        Route::get('order_products','Admin\AdminProductController@order_products')->name('order_products');

        // Document CRUD Operations

        Route::get('documents', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');

        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');

        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');

        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');

        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');

        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');

        // Documents end

        //posts start

        Route::get('posts' , 'Admin\AdminPostController@posts_index')->name('posts.index');

        Route::get('posts/delete', 'Admin\AdminPostController@posts_delete')->name('posts.delete');

        Route::get('posts/create', 'Admin\AdminPostController@posts_create')->name('posts.create');

        Route::get('posts/view', 'Admin\AdminPostController@posts_view')->name('posts.view');

        Route::post('posts/save', 'Admin\AdminPostController@posts_save')->name('posts.save');

        Route::get('posts/edit', 'Admin\AdminPostController@posts_edit')->name('posts.edit');

        Route::get('posts/dashboard', 'Admin\AdminPostController@posts_dashboard')->name('posts.dashboard');

        Route::get('posts/status', 'Admin\AdminPostController@posts_status')->name('posts.status');

        Route::get('posts/publish', 'Admin\AdminPostController@posts_publish')->name('posts.publish');

        Route::get('post/payments','Admin\AdminRevenueController@post_payments')->name('post.payments');

        Route::get('post/payments/view','Admin\AdminRevenueController@post_payments_view')->name('post.payments.view');

        Route::get('post_comments','Admin\AdminPostController@post_comments')->name('posts.comments');

        Route::get('post_comments/delete','Admin\AdminPostController@post_comment_delete')->name('post_comment.delete');

        Route::post('/posts/bulk_action', 'Admin\AdminPostController@posts_bulk_action')->name('posts.bulk_action');


        //posts end

        //posts albums start

        Route::get('post_albums' , 'Admin\AdminPostController@post_albums_index')->name('post_albums.index');

        Route::get('post_albums/delete', 'Admin\AdminPostController@post_albums_delete')->name('post_albums.delete');

        Route::get('post_albums/view', 'Admin\AdminPostController@post_albums_view')->name('post_albums.view');

        Route::get('post_albums/status', 'Admin\AdminPostController@post_albums_status')->name('post_albums.status');

        //posts albums end

        //orders start

        Route::get('orders' , 'Admin\AdminPostController@orders_index')->name('orders.index');

        Route::get('orders/view', 'Admin\AdminPostController@orders_view')->name('orders.view');

        Route::get('order/payments','Admin\AdminRevenueController@order_payments')->name('order.payments');

        Route::get('order/payments/view','Admin\AdminRevenueController@order_payments_view')->name('order.payments.view');

        //orders end

        //delivery address routes start

        Route::get('delivery_address' , 'Admin\AdminPostController@delivery_address_index')->name('delivery_address.index');

        Route::get('delivery_address/delete', 'Admin\AdminPostController@delivery_address_delete')->name('delivery_address.delete');

        Route::get('delivery_address/view', 'Admin\AdminPostController@delivery_address_view')->name('delivery_address.view');

        //delivery address routes end

         //bookmarks routes start

        Route::get('bookmarks' , 'Admin\AdminPostController@post_bookmarks_index')->name('bookmarks.index');

        Route::get('bookmarks/delete', 'Admin\AdminPostController@post_bookmarks_delete')->name('bookmarks.delete');

        Route::get('bookmarks/view', 'Admin\AdminPostController@post_bookmarks_view')->name('bookmarks.view');
         //bookmarks routes start


        // fav users route start
        Route::get('fav_users','Admin\AdminPostController@fav_users')->name('fav_users.index');

        Route::get('fav_users/delete','Admin\AdminPostController@fav_users_delete')->name('fav_users.delete');

        // end of fav user route end


      // liked posts route start
        Route::get('post_likes','Admin\AdminPostController@post_likes')->name('post_likes.index');

        Route::get('post_likes/delete','Admin\AdminPostController@post_likes_delete')->name('post_likes.delete');

        // end of liked posts


        
        //user wallet route start

        Route::get('user_wallets' , 'Admin\AdminRevenueController@user_wallets_index')->name('user_wallets.index');

        Route::get('user_wallets/view', 'Admin\AdminRevenueController@user_wallets_view')->name('user_wallets.view');

        //user wallet route end

        //revenue dashboard start

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        //revenue dashboard end

        //subscriptions start
        Route::get('subscriptions', 'Admin\AdminRevenueController@subscriptions_index')->name('subscriptions.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

Route::get('settings_generate_json', 'ApplicationController@settings_generate_json')->name('settings_generate_json');

Route::get('free_subscriptions_clear', 'UpgradeController@free_subscriptions_clear')->name('free_subscriptions_clear');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $hidden = ['id','unique_id'];

	protected $appends = ['amount_formatted','post_id','post_unique_id', 'username', 'user_displayname','user_picture', 'user_unique_id', 'total_likes', 'total_comments','is_verified_badge','verified_badge_file'];

	public function getAmountFormattedAttribute() {

		return formatted_amount($this->amount);
	}

	public function getPostIdAttribute() {

		return $this->id;
	}

	public function getPostUniqueIdAttribute() {

		return $this->unique_id;
	}

	public function getUserUniqueIdAttribute() {

		$user_unique_id = $this->user->unique_id ?? "";

		// unset($this->user);

		return $user_unique_id ?? "";
	}

	public function getUsernameAttribute() {

		$username = $this->user->username ?? "";

		// unset($this->user);

		return $username ?? "";
	}

	public function getUserDisplaynameAttribute() {

		$name = $this->user->name ?? "";

		// unset($this->user);

		return $name ?? "";
	}

	public function getIsVerifiedBadgeAttribute() {

		$is_verified_badge = $this->user->is_verified_badge ?? "";

		// unset($this->user);

		return $is_verified_badge ?? "";
	}

	public function getUserPictureAttribute() {

		$picture = $this->user->picture ?? "";

		// unset($this->user);

		return $picture ?? "";
	}

	public function getTotalLikesAttribute() {
		
	    return $this->hasMany(PostLike::class, 'post_id')->count();

	}

	public function getTotalCommentsAttribute() {
		
	    return $this->postComments->count();

	}

	public function getVerifiedBadgeFileAttribute() {

        $verified_badge_file = $this->user->is_verified_badge ? \Setting::get('verified_badge_file') : '';

        // unset($this->user);

        return $verified_badge_file ?? "";
    }

	public function user() {

	   return $this->belongsTo(User::class, 'user_id');
	}

	public function postBookmark() {

	    return $this->belongsTo(PostBookmark::class, 'post_id', 'post_id');
	 }

	public function postFiles() {

	   return $this->hasMany(PostFile::class, 'post_id');
	}

	public function postLikes() {

	   return $this->hasMany(PostLike::class, 'post_id');
	}

	public function postComments() {

	   return $this->hasMany(PostComment::class, 'post_id');
	}

	public function postBookmarks() {

	   return $this->hasMany(PostBookmark::class, 'post_id');
	}

	public function postPayments() {

	   return $this->hasMany(PostPayment::class, 'post_id');
	}

	public function reportPosts() {

		return $this->hasMany(ReportPost::class, 'post_id');
	 }

	/**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePaidApproved($query) {

        $query->where('posts.is_published', YES)->where('posts.status', YES)->where('posts.is_paid_post', YES)->where('posts.amount', '>', 0);

        return $query;

    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        $query->where('posts.is_published', YES)->where('posts.status', YES);

        return $query;

    }

	public static function boot() {

        parent::boot();

        static::creating(function ($model) {
            $model->attributes['unique_id'] = "PF"."-".uniqid();
        });

        static::created(function($model) {

            $model->attributes['unique_id'] = "PF"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::deleting(function ($model){

            $model->postLikes()->delete();

            $model->postComments()->delete();

            $model->postPayments()->delete();

            $model->postBookmarks()->delete();

			$model->postFiles()->delete();
			
			$model->reportPosts()->delete();
            
        });

    }
}

app/ReportPost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ReportPost extends Model
{
    //

    protected $fillable = ['post_id', 'block_by','reason'];

    protected $hidden = ['id'];

	protected $appends = ['report_post_id'];
	
	public function getReportPostIdAttribute() {

		return $this->id;
	}

 
    public function blockeduser() {

		return $this->belongsTo(User::class,'block_by');
    }
    
    public function post() {

		return $this->belongsTo(Post::class,'post_id');
	}
	
}

resources/views/admin/posts/report_posts/index.blade.php
@extends('layouts.admin')

@section('title', tr('posts'))

@section('content-header', tr('posts'))

@section('breadcrumb')



<li class="breadcrumb-item active">
    <a href="{{route('admin.posts.index')}}">{{ tr('posts') }}</a>
</li>

<li class="breadcrumb-item active">
    {{tr('view_report_posts')}}
</li>

@endsection

@section('content')

<section id="configuration">

    <div class="row">

        <div class="col-12">

            <div class="card report-post-sec">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">

                        {{ tr('view_report_posts') }}

                    </h4>

                    <div class="heading-elements">


                    </div>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>

                </div>

                <div class="card-content collapse show">

                    <div class="card-body card-dashboard">


                        <table class="table table-striped table-bordered sourced-data">

                            <thead>
                                <tr>

                                    <th>{{ tr('s_no') }}</th>
                                    <th>{{ tr('post') }}</th>
                                    <th>{{ tr('report_user_count') }}</th>
                                    <th>{{ tr('action') }}</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach($report_posts as $i => $post)
                                <tr>
                                    <td>{{ $i+$report_posts->firstItem() }}</td>

                                    <td>

                                        <a href="{{route('admin.posts.view',['post_id'=>$post->post->id ?? ''])}}">
                                            {{$post->post->post_unique_id ?? '' }}
                                        </a>

                                    </td>

                                    <td>
                                        <a class="custom-a" href="{{route('admin.report_posts.view',['post_id'=>$post->post_id])}}">
                                            {{$post->report_user_count }}
                                        </a>
                                    </td>

                                    <td>

                                        <div class="btn-group" role="group">

                                            <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-right" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ft-settings icon-left"></i> {{ tr('action') }}</button>

                                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                                <a class="dropdown-item" href="{{route('admin.report_posts.view',['post_id'=>$post->post_id])}}">&nbsp;{{ tr('view') }}</a>

                                                @if($post->post->status == APPROVED)

                                                <a class="dropdown-item" href="{{  route('admin.posts.status' , ['post_id' => $post->post_id] )  }}" onclick="return confirm(&quot;{{ tr('post_decline_confirmation') }}&quot;);">&nbsp;{{ tr('decline') }}
                                                </a>

                                                @else

                                                <a class="dropdown-item" href="{{ route('admin.posts.status' , ['post_id' => $post->post_id] ) }}">&nbsp;{{ tr('approve') }}</a>

                                                @endif

                                                <a class="dropdown-item" onclick="return confirm(&quot;{{ tr('post_delete_confirmation' , $post->unique_id) }}&quot;);" href="{{ route('admin.posts.delete', ['post_id' => $post->post_id,'page'=>request()->input('page')] ) }}">&nbsp;{{ tr('delete') }}</a>

                                                <a class="dropdown-item" onclick="return confirm(&quot; {{ tr('delete_confirmation') }}&quot;);" href="{{route('admin.report_posts.delete',['post_id'=>$post->post_id])}}">&nbsp;{{ tr('delete_report') }}</a>

                                            </div>
                                        </div>
                                    </td>

                                </tr>

                                @endforeach

                            </tbody>

                        </table>

                        <div class="pull-right resp-float-unset" id="paglink">{{ $report_posts->appends(request()->input())->links() }}</div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>

@endsection

resources/views/admin/posts/report_posts/view.blade.php
@extends('layouts.admin')

@section('title', tr('posts'))

@section('content-header', tr('report_posts'))

@section('breadcrumb')



<li class="breadcrumb-item active">
    <a href="{{route('admin.posts.index')}}">{{ tr('posts') }}</a>
</li>

<li class="breadcrumb-item active">
    {{tr('view_report_posts')}}
</li>

@endsection

@section('content')

<section id="configuration">

    <div class="row">

        <div class="col-12">

            <div class="card">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">

                        {{ tr('view_report_posts') }} -

                        <a href="{{route('admin.posts.view',['post_id'=>$post->id ?? ''])}}">{{$post->post_unique_id ?? ''}}</a>

                    </h4>

                    <div class="heading-elements">

                        <a onclick="return confirm(&quot;{{ tr('post_delete_confirmation' , $post->post_unique_id ?? '') }}&quot;);" href="{{ route('admin.posts.delete', ['post_id' => $post->id,'page'=>request()->input('page')] ) }}" class="btn btn-primary"><i class="ft-trash icon-left"></i>{{tr('delete_post')}}</a>
                   
                    </div>


                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>

                </div>

                <div class="card-content collapse show">

                    <div class="card-body card-dashboard">


                        <table class="table table-striped table-bordered sourced-data table-responsive">

                            <thead>
                                <tr>

                                    <th>{{ tr('s_no') }}</th>
                                    <th>{{ tr('post') }}</th>
                                    <th>{{ tr('report_user') }}</th>
                                    <th>{{ tr('reason') }}</th>
                                    <th>{{ tr('action') }}</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach($report_posts as $i => $report_post)
                                <tr>
                                    <td>{{ $i+$report_posts->firstItem() }}</td>

                                    <td>

                                        <a href="{{route('admin.posts.view',['post_id'=>$report_post->post->id ?? ''])}}">
                                            {{$report_post->post->post_unique_id ?? '' }}
                                        </a>

                                    </td>

                                    <td>
                                        <a href="{{route('admin.users.view',['user_id'=>$report_post->block_by ?? ''])}}">
                                            {{$report_post->blockeduser->name ?? '' }}
                                        </a>
                                    </td>

                                    <td>{{$report_post->reason ?? '' }}</td>


                                    <td>

                                        <a class="btn btn-outline-warning btn-large" onclick="return confirm(&quot; {{ tr('delete_confirmation') }}&quot;);" href="{{route('admin.report_posts.delete',['report_post_id'=>$report_post->id])}}">&nbsp;{{ tr('delete_report') }}</a>

                                    </td>

                                </tr>

                                @endforeach

                            </tbody>

                        </table>

                        <div class="pull-right" id="paglink">{{ $report_posts->appends(request()->input())->links() }}</div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>

@endsection