routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');

        Route::get('/', 'Admin\AdminRevenueController@main_dashboard')->name('dashboard');
        
        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/verify_badge', 'Admin\AdminUserController@users_verify_badge_status')->name('users.verify_badge');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/billing_accounts','Admin\AdminUserController@billing_accounts_index')->name('users.billing_accounts');


        Route::get('user_subscription_payments/index','Admin\AdminUserController@user_subscription_payments')->name('users_subscriptions.index');

        Route::get('user_subscriptions_payment/view','Admin\AdminUserController@user_subscriptions_payment_view')->name('user_subscriptions.view');

        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        Route::get('users/upgrade_account', 'Admin\AdminUserController@user_upgrade_account')->name('users.upgrade_account');

        //followers
         Route::get('followers' , 'Admin\AdminUserController@user_followers')->name('user_followers');

        Route::get('followings', 'Admin\AdminUserController@user_followings')->name('user_followings');

        //user products CRUD Operations

        Route::get('products', 'Admin\AdminProductController@user_products_index')->name('user_products.index');

        Route::get('products/create', 'Admin\AdminProductController@user_products_create')->name('user_products.create');

        Route::get('products/edit', 'Admin\AdminProductController@user_products_edit')->name('user_products.edit');

        Route::post('products/save', 'Admin\AdminProductController@user_products_save')->name('user_products.save');

        Route::get('products/view', 'Admin\AdminProductController@user_products_view')->name('user_products.view');

        Route::get('products/delete', 'Admin\AdminProductController@user_products_delete')->name('user_products.delete');

        Route::get('products/status', 'Admin\AdminProductController@user_products_status')->name('user_products.status');

        Route::get('products/dashboard', 'Admin\AdminProductController@user_products_dashboard')->name('user_products.dashboard');

        Route::get('order_products','Admin\AdminProductController@order_products')->name('order_products');

        // Document CRUD Operations

        Route::get('documents', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');

        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');

        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');

        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');

        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');

        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');

        // Documents end

        //posts start

        Route::get('posts' , 'Admin\AdminPostController@posts_index')->name('posts.index');

        Route::get('posts/delete', 'Admin\AdminPostController@posts_delete')->name('posts.delete');

        Route::get('posts/create', 'Admin\AdminPostController@posts_create')->name('posts.create');

        Route::get('posts/view', 'Admin\AdminPostController@posts_view')->name('posts.view');

        Route::post('posts/save', 'Admin\AdminPostController@posts_save')->name('posts.save');

        Route::get('posts/edit', 'Admin\AdminPostController@posts_edit')->name('posts.edit');

        Route::get('posts/dashboard', 'Admin\AdminPostController@posts_dashboard')->name('posts.dashboard');

        Route::get('posts/status', 'Admin\AdminPostController@posts_status')->name('posts.status');

        Route::get('posts/publish', 'Admin\AdminPostController@posts_publish')->name('posts.publish');

        Route::get('post/payments','Admin\AdminRevenueController@post_payments')->name('post.payments');

        Route::get('post/payments/view','Admin\AdminRevenueController@post_payments_view')->name('post.payments.view');

        Route::get('post_comments','Admin\AdminPostController@post_comments')->name('posts.comments');

        Route::get('post_comments/delete','Admin\AdminPostController@post_comment_delete')->name('post_comment.delete');

        Route::post('/posts/bulk_action', 'Admin\AdminPostController@posts_bulk_action')->name('posts.bulk_action');


        //posts end

        //posts albums start

        Route::get('post_albums' , 'Admin\AdminPostController@post_albums_index')->name('post_albums.index');

        Route::get('post_albums/delete', 'Admin\AdminPostController@post_albums_delete')->name('post_albums.delete');

        Route::get('post_albums/view', 'Admin\AdminPostController@post_albums_view')->name('post_albums.view');

        Route::get('post_albums/status', 'Admin\AdminPostController@post_albums_status')->name('post_albums.status');

        //posts albums end

        //orders start

        Route::get('orders' , 'Admin\AdminPostController@orders_index')->name('orders.index');

        Route::get('orders/view', 'Admin\AdminPostController@orders_view')->name('orders.view');

        Route::get('order/payments','Admin\AdminRevenueController@order_payments')->name('order.payments');

        Route::get('order/payments/view','Admin\AdminRevenueController@order_payments_view')->name('order.payments.view');

        //orders end

        //delivery address routes start

        Route::get('delivery_address' , 'Admin\AdminPostController@delivery_address_index')->name('delivery_address.index');

        Route::get('delivery_address/delete', 'Admin\AdminPostController@delivery_address_delete')->name('delivery_address.delete');

        Route::get('delivery_address/view', 'Admin\AdminPostController@delivery_address_view')->name('delivery_address.view');

        //delivery address routes end

         //bookmarks routes start

        Route::get('bookmarks' , 'Admin\AdminPostController@post_bookmarks_index')->name('bookmarks.index');

        Route::get('bookmarks/delete', 'Admin\AdminPostController@post_bookmarks_delete')->name('bookmarks.delete');

        Route::get('bookmarks/view', 'Admin\AdminPostController@post_bookmarks_view')->name('bookmarks.view');
         //bookmarks routes start


        // fav users route start
        Route::get('fav_users','Admin\AdminPostController@fav_users')->name('fav_users.index');

        Route::get('fav_users/delete','Admin\AdminPostController@fav_users_delete')->name('fav_users.delete');

        // end of fav user route end


      // liked posts route start
        Route::get('post_likes','Admin\AdminPostController@post_likes')->name('post_likes.index');

        Route::get('post_likes/delete','Admin\AdminPostController@post_likes_delete')->name('post_likes.delete');

        // end of liked posts


        
        //user wallet route start

        Route::get('user_wallets' , 'Admin\AdminRevenueController@user_wallets_index')->name('user_wallets.index');

        Route::get('user_wallets/view', 'Admin\AdminRevenueController@user_wallets_view')->name('user_wallets.view');

        //user wallet route end

        //revenue dashboard start

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        //revenue dashboard end

        //subscriptions start
        Route::get('subscriptions', 'Admin\AdminRevenueController@subscriptions_index')->name('subscriptions.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

Route::get('settings_generate_json', 'ApplicationController@settings_generate_json')->name('settings_generate_json');

Route::get('free_subscriptions_clear', 'UpgradeController@free_subscriptions_clear')->name('free_subscriptions_clear');

app/PostAlbum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostAlbum extends Model
{	

	protected $appends = ['post_album_id','post_album_unique_id'];

	protected $hidden = ['id','unique_id'];

	public function getPostAlbumIdAttribute() {

		return $this->id;
	}

	public function getPostAlbumUniqueIdAttribute() {

		return $this->unique_id;
	}

    public function user() {

    	return $this->belongsTo(User::class,'user_id');
    }
}

resources/views/admin/post_albums/index.blade.php
@extends('layouts.admin') 

@section('title', tr('post_albums')) 

@section('content-header', tr('post_albums')) 

@section('breadcrumb')


    
<li class="breadcrumb-item active">
    <a href="">{{ tr('post_albums') }}</a>
</li>

<li class="breadcrumb-item active">{{ tr('view_post_albums') }}</li>

@endsection 

@section('content')

<section id="configuration">

    <div class="row">

        <div class="col-12">

            <div class="card">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">{{ tr('view_post_albums') }}</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    
                </div>

                <div class="card-content collapse show">

                    <div class="card-body card-dashboard">


                        <table class="table table-striped table-bordered sourced-data table-responsive">
                            
                            <thead>
                                <tr>
                                    <th>{{ tr('s_no') }}</th>
                                    <th>{{ tr('unique_id') }}</th>
                                    <th>{{ tr('name') }}</th>
                                    <th>{{ tr('content_creator') }}</th>
                                    <th>{{ tr('status') }}</th>
                                    <th>{{ tr('action') }}</th>
                                </tr>
                            </thead>
                           
                            <tbody>

                                @foreach($post_albums as $i => $post_album)
                                <tr>
                                    <td>{{ $i+$post_albums->firstItem() }}</td>

                                    <td>{{$post_album->unique_id}}</td>

                                    <td>{{$post_album->name}}</td>

                                    <td>
                                        <a href="{{  route('admin.users.view' , ['user_id' => $post_album->user_id] )  }}">
                                        {{ $post_album->user->name ?? "-" }}
                                        </a>
                                    </td>

                                    <td>
                                        @if($post_album->status == APPROVED)

                                        <span class="btn btn-success btn-sm">{{ tr('approved') }}</span> @else

                                        <span class="btn btn-warning btn-sm">{{ tr('declined') }}</span> @endif
                                    </td>


                                    <td>
                                    
                                        <div class="btn-group" role="group">

                                            <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-right" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ft-settings icon-left"></i> {{ tr('action') }}</button>

                                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                                <a class="dropdown-item" href="{{ route('admin.post_albums.view', ['post_album_id' => $post_album->id] ) }}">&nbsp;{{ tr('view') }}</a> 

                                                @if(Setting::get('is_demo_control_enabled') == YES)

                                                  

                                                    <a class="dropdown-item" href="javascript:void(0)">&nbsp;{{ tr('delete') }}</a> 

                                                @else

                                                    <a class="dropdown-item" onclick="return confirm(&quot;{{ tr('post_album_delete_confirmation' , $post_album->name) }}&quot;);" href="{{ route('admin.post_albums.delete', ['post_album_id' => $post_album->id] ) }}">&nbsp;{{ tr('delete') }}</a>

                                                @endif

                                                @if($post_album->status == APPROVED)

                                                    <a class="dropdown-item" href="{{  route('admin.post_albums.status' , ['post_album_id' => $post_album->id] )  }}" onclick="return confirm(&quot;{{ tr('post_album_decline_confirmation') }}&quot;);">&nbsp;{{ tr('decline') }}
                                                </a> 

                                                @else

                                                    <a class="dropdown-item" href="{{ route('admin.post_albums.status' , ['post_album_id' => $post_album->id] ) }}">&nbsp;{{ tr('approve') }}</a> 

                                                @endif

                                            </div>

                                        </div>

                                    </td>

                                </tr>

                                @endforeach

                            </tbody>
                        
                        </table>

                        <div class="pull-right" id="paglink">{{ $post_albums->appends(request()->input())->links() }}</div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>

@endsection

resources/views/admin/post_albums/view.blade.php
@extends('layouts.admin')

@section('title', tr('post_albums'))

@section('content-header', tr('post_albums'))

@section('breadcrumb')

    <li class="breadcrumb-item active"><a href="{{route('admin.post_albums.index')}}">{{tr('post_albums')}}</a>
    </li>

    <li class="breadcrumb-item">{{tr('view_post_albums')}}</li>

@endsection

@section('content')

<div class="content-body">

    <div class="col-12">

        <div class="card">

            <div class="card-header border-bottom border-gray">

                <h4 class="card-title">{{ tr('view_post_albums') }}</h4>
                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                
            </div>

            <div class="text-center">

                <div class="card-body">
                    <img src="{{$post_album->user->picture ?? asset('placeholder.jpeg')}}" class="rounded-circle height-100" alt="Card image" />
                </div>

                <div class="card-body">
                    <h4 class="card-title">{{$post_album->user->name ?? "-"}}</h4>
                    <h6 class="card-subtitle text-muted">{{$post_album->user->email ?? "-"}}</h6>
                </div>

                <div class="text-center">

                    <a href="{{route('admin.users.view',['user_id' => $post_album->user_id])}}" class="btn btn-primary">
                        {{tr('go_to_profile')}}
                    </a>

                    @if(Setting::get('is_demo_control_enabled') == YES)

                        <a class="btn btn-danger" href="javascript:void(0)">&nbsp;{{ tr('delete') }}</a> 

                    @else

                        <a class="btn btn-danger" onclick="return confirm(&quot;{{ tr('post_album_delete_confirmation' , $post_album->name) }}&quot;);" href="{{ route('admin.post_albums.delete', ['post_album_id' => $post_album->id] ) }}">&nbsp;{{ tr('delete') }}</a>

                    @endif

                    @if($post_album->status == APPROVED)

                        <a class="btn btn-danger" href="{{  route('admin.post_albums.status' , ['post_album_id' => $post_album->id] )  }}" onclick="return confirm(&quot;{{ tr('post_album_decline_confirmation') }}&quot;);">&nbsp;{{ tr('decline') }}
                    </a> 

                    @else

                        <a class="btn btn-success" href="{{ route('admin.post_albums.status' , ['post_album_id' => $post_album->id] ) }}">&nbsp;{{ tr('approve') }}</a> 

                    @endif
                   
                </div>

                <hr>

            </div>

            <div class="row">

                <div class="col-6">
                    
                    <ul>
                        <li class="text-uppercase">{{tr('unique_id')}} - {{$post_album->unique_id}}</li>
                        <hr>

                        <li>{{tr('name')}} - {{$post_album->name}}</li>
                        <hr>

                        <li>{{tr('status')}} - 

                            @if($post_album->status == APPROVED)

                                <span class="btn btn-success btn-sm">{{ tr('approved') }}</span> 
                            @else

                                <span class="btn btn-warning btn-sm">{{ tr('declined') }}</span> 
                            @endif
                        </li>
                        <hr>

                    </ul>
                </div>

                <div class="col-6">

                    <ul>
                        
                        <li>{{tr('created_at')}} - {{common_date($post_album->created_at , Auth::guard('admin')->user()->timezone)}}</li>
                        <hr>

                        <li>{{tr('updated_at')}} - {{common_date($post_album->updated_at , Auth::guard('admin')->user()->timezone)}}</li>
                        <hr>

                    </ul>

                </div>

            </div>

            <hr>
            
            <section id="image-gallery" class="card">

                <div class="card-header">

                    <h4 class="card-title">Image gallery</h4>
                   
                </div>

                <div class="card-content">
                    
                    <div class="card-body my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
                        <div class="row">
                            @foreach($posts as $post)
                            <figure class="col-lg-3 col-md-6 col-12" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
                                <a href="" itemprop="contentUrl" data-size="480x360">
                                    <img class="img-thumbnail img-fluid" src="{{$post->picture}}" itemprop="thumbnail" alt="Image description" />
                                </a>
                            </figure>
                            @endforeach

                        </div>
                    </div>
                    
                </div>

            </section>
   

        </div>

    </div>

</div>
  
@endsection